<ul id="links">
	<li><a href="index.php">Home</a></li>
	<li class="dropdown">
		<a class="m" href="#">Downloads</a>
		<div class="dropdownC">
			<a href="#">Games</a>
			<a href="#">Tools</a>
			<a href="videos.php">Videos</a>
		</div>
	</li>
	<li><a href="stories.php">Stories</a></li>
	<li><a href="contact.php">Contact</a></li>
	<li><a href="about.php">About</a></li>
	<li class="dropdown">
		<a href="#">Links</a>
		<div class="dropdownC">
			<a href="ZF3000/index.php">ZF3000</a>
			<a href="./new/">The Most Boss new thing</a>
		</div>
	</li>
</ul>
