runtime: php55
api_version: 1
threadsafe: ture

handlers:
- url: /(.*\.(css|js|svg|png|jpg))
  static_files: \1
  upload: (.*\.(css|js|svg|png|jpg))

- url: /.+
  script: \1

- url: /.*
  script: index.php


# runtime: php72
#
# runtime_config:
#   document_root: web
#
# handlers:
# - url: /(.*\.(htm$|html$|css$|js$))
#   static_files: \1
#
#   upload: (.*\.(htm$|html$|css$|js$))
#   application_readable: true
#
# - url: /(.*\.(ico$|jpg$|png$|gif$))
#   static_files: \1
#
#   upload: (.*\.(ico$|jpg$|png$|gif$))
#   application_readable: true
#
# - url: /(.+)
#   script: \1
#
# - url: /.*
#   script: index.php
